#!/usr/bin/env bash
#
# Increases saturation automatically when playing CS:GO
#

LOCATION="$(readlink -f $0)"

NAME="AutomaticVibrance"
LOGFILE="/dev/null"

RUN="$LOCATION --launch"

if [[ $1 == "--launch" ]] || [[ $1 == "-l" ]]; then
	while true; do
		# Wait for the game to start
		while ! pgrep csgo_linux64 > /dev/null; do
			sleep 1
		done

		nvidia-settings -a "DigitalVibrance=716" > /dev/null

		# Wait for the game to end
		while pgrep csgo_linux64 > /dev/null; do
			sleep 1
		done

		nvidia-settings -a "DigitalVibrance=0" > /dev/null
	done
elif [[ $1 == "--background" ]] || [[ $1 == "-bg" ]]; then
	if pgrep -f "$RUN" > /dev/null; then
		echo $NAME is already running.
	else
		nohup bash $RUN --launch > $LOGFILE 2>&1 &
		echo Started $NAME in background.
	fi
elif [[ $1 == "--stop" ]] || [[ $1 == "-s" ]]; then
	if pgrep -f "$RUN" > /dev/null; then
		pgrep -f "$RUN" | xargs kill > /dev/null
		nvidia-settings -a "DigitalVibrance=0" > /dev/null
		echo $NAME has stopped.
	else
		echo $NAME already not running.
	fi
else
	echo "$NAME V1"
	echo "Usage: $NAME [option]"
	echo
	echo "  --background, -bg    launches the script in background"
	echo "  --stop,       -s     stops the script"
	echo "  --launch,     -l     executes the script"
fi
